name: fancy_button
description: A useless fancy button.
version: 0.0.3
author: Seth Ladd <sethladd@gmail.com>
homepage: http://later
dependencies:
  polymer: ">=0.10.0-pre.13 <0.11.0"
transformers:
- polymer
